# Generated by Django 6.0.6 on 2026-08-27 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProxyGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64, unique=True)),
                ('description', models.CharField(blank=True, default='', max_length=256)),
                ('country', models.CharField(blank=True, default='', max_length=64)),
                ('enabled', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'proxy_group',
            },
        ),
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64, unique=True)),
                ('value', models.TextField(blank=True, default='')),
                ('description', models.CharField(blank=True, default='', max_length=256)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'system_setting',
            },
        ),
        migrations.CreateModel(
            name='UserApiKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128)),
                ('key_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('key_prefix', models.CharField(max_length=32)),
                ('enabled', models.BooleanField(default=True)),
                ('rate_limit', models.IntegerField(default=120, help_text='requests per minute')),
                ('total_requests', models.IntegerField(default=0)),
                ('success_requests', models.IntegerField(default=0)),
                ('failed_requests', models.IntegerField(default=0)),
                ('minute_window_start', models.DateTimeField(blank=True, null=True)),
                ('minute_request_count', models.IntegerField(default=0)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user_api_key',
            },
        ),
        migrations.CreateModel(
            name='AIModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('model_name', models.CharField(max_length=256, unique=True)),
                ('display_name', models.CharField(blank=True, default='', max_length=256)),
                ('description', models.TextField(blank=True, default='')),
                ('provider', models.CharField(default='nvidia', max_length=64)),
                ('status', models.CharField(default='active', max_length=16)),
                ('enabled', models.BooleanField(db_index=True, default=False)),
            ],
            options={
                'db_table': 'model',
                'indexes': [models.Index(fields=['enabled', 'model_name'], name='model_enabled_29c2a3_idx')],
            },
        ),
        migrations.CreateModel(
            name='NvidiaApiKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128)),
                ('api_key', models.CharField(max_length=256, unique=True)),
                ('status', models.CharField(choices=[('available', 'Available'), ('rate_limited', 'Rate limited'), ('error', 'Error'), ('disabled', 'Disabled'), ('invalid', 'Invalid')], db_index=True, default='available', max_length=16)),
                ('rpm_limit', models.IntegerField(default=40)),
                ('minute_window_start', models.DateTimeField(blank=True, null=True)),
                ('minute_request_count', models.IntegerField(default=0)),
                ('success_count', models.IntegerField(default=0)),
                ('failure_count', models.IntegerField(default=0)),
                ('cooldown_until', models.DateTimeField(blank=True, null=True)),
                ('last_used_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('last_error', models.CharField(blank=True, default='', max_length=256)),
            ],
            options={
                'db_table': 'nvidia_api_key',
                'indexes': [models.Index(fields=['status', 'last_used_at'], name='nvidia_api__status_0f72a2_idx')],
            },
        ),
        migrations.CreateModel(
            name='Proxy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128)),
                ('protocol', models.CharField(default='socks5', max_length=16)),
                ('host', models.CharField(max_length=255)),
                ('port', models.IntegerField()),
                ('username', models.CharField(blank=True, default='', max_length=128)),
                ('password', models.CharField(blank=True, default='', max_length=128)),
                ('country', models.CharField(blank=True, default='', max_length=64)),
                ('region', models.CharField(blank=True, default='', max_length=64)),
                ('city', models.CharField(blank=True, default='', max_length=64)),
                ('isp', models.CharField(blank=True, default='', max_length=128)),
                ('enabled', models.BooleanField(db_index=True, default=False)),
                ('status', models.CharField(choices=[('unknown', 'Unknown'), ('healthy', 'Healthy'), ('degraded', 'Degraded'), ('unhealthy', 'Unhealthy'), ('disabled', 'Disabled')], db_index=True, default='unknown', max_length=16)),
                ('latency_ms', models.FloatField(blank=True, null=True)),
                ('public_ip', models.CharField(blank=True, default='', max_length=64)),
                ('last_check_at', models.DateTimeField(blank=True, null=True)),
                ('success_count', models.IntegerField(default=0)),
                ('failure_count', models.IntegerField(default=0)),
                ('consecutive_failures', models.IntegerField(default=0)),
                ('cooldown_until', models.DateTimeField(blank=True, null=True)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proxies', to='core.proxygroup')),
            ],
            options={
                'db_table': 'proxy',
                'indexes': [models.Index(fields=['enabled', 'status'], name='proxy_enabled_c27121_idx')],
                'constraints': [models.UniqueConstraint(fields=('protocol', 'host', 'port', 'username'), name='unique_proxy_endpoint')],
            },
        ),
        migrations.CreateModel(
            name='RequestLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.CharField(db_index=True, max_length=40)),
                ('model', models.CharField(db_index=True, max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('duration_ms', models.FloatField(default=0)),
                ('status', models.CharField(db_index=True, default='pending', max_length=16)),
                ('http_status', models.IntegerField(default=0)),
                ('error_type', models.CharField(blank=True, default='', max_length=64)),
                ('winner_route_type', models.CharField(blank=True, default='', max_length=16)),
                ('winner_key_name', models.CharField(blank=True, default='', max_length=128)),
                ('winner_proxy_name', models.CharField(blank=True, default='', max_length=128)),
                ('proxy_public_ip', models.CharField(blank=True, default='', max_length=64)),
                ('is_stream', models.BooleanField(default=False)),
                ('routes_count', models.IntegerField(default=0)),
                ('prompt_tokens', models.IntegerField(default=0)),
                ('completion_tokens', models.IntegerField(default=0)),
                ('total_tokens', models.IntegerField(default=0)),
                ('user_api_key', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='core.userapikey')),
            ],
            options={
                'db_table': 'request_log',
                'indexes': [models.Index(fields=['created_at', 'status'], name='request_log_created_f29d6d_idx')],
            },
        ),
    ]
