# Generated by Django 6.0.6 on 2026-08-28 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userapikey',
            name='rate_limit',
            field=models.IntegerField(default=0, help_text='requests per minute, 0 = unlimited'),
        ),
    ]
