# Generated by Django 6.0.6 on 2026-08-28 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_userapikey_rate_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestlog',
            name='routes',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
