# Generated by Django 6.0.6 on 2026-08-28 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_requestlog_routes'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestlog',
            name='cached_tokens',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='requestlog',
            name='first_token_ms',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
