# Generated by Django 6.1
from django.db import migrations, models


class Migration(migrations.Migration):
    """渠道允许导入重复 Key（zen/kilo），并去除 channelkey 的硬唯一约束。"""
    dependencies = [
        ("core", "0006_model_alias_priority"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="channelkey",
            name="unique_channel_key",
        ),
        migrations.AddField(
            model_name="channel",
            name="allow_duplicate_keys",
            field=models.BooleanField(default=False),
        ),
    ]
