# Generated by Django 6.1 on 2026-08-29 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_channelkey_unique_channel_key_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='channelkey',
            new_name='channel_key_status_e75db5_idx',
            old_name='nvidia_api__status_0f72a2_idx',
        ),
    ]
