# Generated by Django 6.1 on 2026-08-29 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rename_nvidia_api__status_0f72a2_idx_channel_key_status_e75db5_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimodel',
            name='proxy_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='models', to='core.proxygroup'),
        ),
        migrations.AddField(
            model_name='requestlog',
            name='upstream_thinking',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
