# Generated by Django 6.1 on 2026-08-29 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_add_upstream_thinking_and_model_proxy_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestlog',
            name='client_thinking',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
