# Generated by Django 6.1 on 2026-08-29 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_add_client_thinking'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='disable_key_invalid',
            field=models.BooleanField(default=False),
        ),
    ]
