# Generated by Django 6.1 on 2026-08-29 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_channel_disable_key_invalid'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimodel',
            name='endpoint',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
    ]
