# Generated by Django 6.1 on 2026-08-30 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_add_model_endpoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='userapikey',
            name='quota',
            field=models.BigIntegerField(default=0, help_text='total token quota, 0 = unlimited'),
        ),
        migrations.AddField(
            model_name='userapikey',
            name='used_quota',
            field=models.BigIntegerField(default=0, help_text='accumulated token usage'),
        ),
    ]
