# Generated by Django 6.1 on 2026-08-30 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_add_user_key_quota'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='consecutive_failures',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='channel',
            name='cooldown_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
