# Generated by Django 6.1 on 2026-08-30 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_add_channel_circuit_breaker'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimodel',
            name='aliases',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
