# Generated by Django 6.1 on 2026-08-30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_aimodel_aliases'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='disable_proxy_unhealthy',
            field=models.BooleanField(default=False),
        ),
    ]
