# Generated by Django 6.1 on 2026-08-30 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_channel_disable_proxy_unhealthy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channelkey',
            name='api_key',
            field=models.TextField(),
        ),
    ]
