# Generated by Django 6.1 on 2026-09-02 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_channelkey_api_key_textfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='channelkey',
            name='api_key_hint',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
