# Generated by Django 6.1 on 2026-09-04 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_backfill_api_key_hint'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestlog',
            name='request_summary',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
