# Generated by Django 6.1 on 2026-09-04 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_request_summary_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proxy',
            name='password',
            field=models.TextField(blank=True, default=''),
        ),
    ]
