# Generated by Django 6.1 on 2026-09-04 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_proxy_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecretAccessLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('action', models.CharField(choices=[('reveal_key', '回看上游 Key 明文')], db_index=True, max_length=32)),
                ('target_id', models.IntegerField(blank=True, null=True)),
                ('target_name', models.CharField(blank=True, default='', max_length=128)),
                ('remote_addr', models.CharField(blank=True, default='', max_length=64)),
                ('forwarded_for', models.CharField(blank=True, default='', max_length=256)),
                ('user_agent', models.CharField(blank=True, default='', max_length=256)),
                ('channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secret_access_logs', to='core.channel')),
            ],
            options={
                'db_table': 'secret_access_log',
                'indexes': [models.Index(fields=['created_at', 'action'], name='secret_acce_created_22a313_idx')],
            },
        ),
    ]
