# Generated by Django 6.1 on 2026-09-06 20:12
"""交付量观测列：stream_chunks / content_chars / reasoning_chars。

上游截断的两种形态此前在日志里完全同形（completion_tokens 都是 0——usage 帧永远在
截断之后才到），但处置**相反**：静默被掐该换线重跑；思考流了很久被掐绝不能换线
（字节已逐块下发给客户端，重跑即重复交付）。没有这三个计数就只能猜。
null = 非流式请求或历史行，与"流式但零 chunk"（0）区分。

SQLite 下可空无默认值的 ADD COLUMN 是 O(1) 元数据操作，不触发 500MB 表重建。
"""

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_requestlog_index_restructure'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestlog',
            name='content_chars',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requestlog',
            name='reasoning_chars',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requestlog',
            name='stream_chunks',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
